List employeeData = [
  {
    'employee_id': 1,
    'first_name': "Bennet",
    'last_name': "Dumashie",
    'age': 29,
    'gender': "Male",
    'sleep_count': 17,
  },
  {
    'employee_id': 2,
    'first_name': "Kweku",
    'last_name': "Bright",
    'age': 35,
    'gender': "Male",
    'sleep_count': 25,
  },
  {
    'employee_id': 3,
    'first_name': "Nii",
    'last_name': "Darku",
    'age': 23,
    'gender': "Male",
    'sleep_count': 16,
  },
  {
    'employee_id': 4,
    'first_name': "Miriam",
    'last_name': "Laate",
    'age': 26,
    'gender': "Female",
    'sleep_count': 20,
  },
  {
    'employee_id': 5,
    'first_name': "Jesus",
    'last_name': "Lobede",
    'age': 29,
    'gender': "Male",
    'sleep_count': 12,
  },
  {
    'employee_id': 6,
    'first_name': "Qwophi",
    'last_name': "Ahwireng",
    'age': 40,
    'gender': "Male",
    'sleep_count': 5,
  },
];
